apiVersion: cloudnativetoolkit.dev/v1alpha1
kind: BillOfMaterial
metadata:
  name: new-cluster
spec:
  modules:
    - name: ibm-vpc
      alias: ibm-vpc
      version: v1.16.1
      variables:
      - name: name
        value: "tsuedbro-ta-gitops"
      - name: tags
        value: ["tsuedbro"]
    - name: ibm-vpc-subnets
      alias: ibm-vpc-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 1
        - name: name
          value: "tsuedbro-ta-gitops"
        - name: tags
          value: ["tsuedbro"]
    - name: ibm-vpc-gateways
    - name: ibm-ocp-vpc
      alias: ibm-ocp-vpc
      version: v1.15.7
      variables:
        - name: name
          value: "tsuedbro-ta-gitops"
        - name: worker_count
          value: 2
        - name: tags
          value: ["tsuedbro"]
    - name: ibm-object-storage
      alias: ibm-object-storage
      version: v4.0.3
      variables:
        - name: name
          value: "tsuedbro-ta-gitops"
        - name: tags
          value: ["tsuedbro"]
        - name: label
          value: ["tsuedbro"]
    - name: argocd-bootstrap
      alias: argocd-bootstrap
      version: v1.12.0
      variables:
        - name: repo_token
    - name: gitops-repo
      alias: gitops-repo
      version: v1.20.2
      variables:
        - name: host
          value: "github.com"
        - name: type
          value: "GIT"
        - name: org
          value: "nheidloff"
        - name: username
          value: "nheidloff"
        - name: project
          value: "ta-gitops"
        - name: repo
          value: "ta-gitops"
    - name: terraform-gitops-guestbook-helm